#!C:/Program\ Files/Git/usr/bin/sh.exe

echo "-----------------Running unit test---------------"

./gradlew.bat test

statusTest=$?

if [[ $statusTest -ne 0 ]]
then
  echo "-----------------Run test fail (fix test)---------------"
  exit $statusTest
else
  echo "-----------------Run test done--------------------------"
  exit $statusTest
fi
