#!/bin/bash

echo "-----------------Running lint check---------------"

./gradlew  ktlintCheck

status=$?

echo "-----------------Running unit test---------------"

./gradlew test

status=$?

echo "-----------------Done with unit test---------------"

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
