#!/bin/bash

echo "-----------------Running lint check---------------"

./gradlew  ktlintCheck

echo "-----------------Running unit test---------------"

./gradlew test

echo "-----------------Done with unit test---------------"

status=$?

# return 1 exit code if running checks fails
[ $status -ne 0 ] && exit 1
exit 0
