#!/bin/bash

echo "-----------------Running lint check---------------"

./gradlew  ktlintCheck

statusLint=$?

[ $statusLint -ne 0 ] && exit 1
exit 0

echo "-----------------Running unit test---------------"

./gradlew test

statusTest=$?

[ $statusTest -ne 0 ] && exit 1
exit 0

echo "-----------------Done with unit test---------------"
