#!/bin/bash

echo "-----------------Running unit test---------------"

./gradlew test

statusTest=$?

if [[ $statusTest -ne 0 ]]
then
  echo "-----------------Run test fail (fix test)---------------"
  exit 1
else
  echo "-----------------Run test done--------------------------"
  exit 0
fi
